spring:
  cloud:
    gcp:
      sql:
        database-name: cm
        instance-connection-name: hallowed-span-378416:europe-west1:cm
        ip-types: PUBLIC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql::///cm
    username: postgres
    password: root
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.mysql.SocketFactory
        cloudSqlInstance: hallowed-span-378416:europe-west1:cm

  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: management
    driver-class-name: org.postgresql.Driver
    schemas: system, management

client-application:
  url: localhost
  port: 8080

google:
  cloud:
    bucket-name: cm-bucket-homework
    project-id: course-management
    credentials-json-path: google_cloud_storage.json